JoypadUp		equ	$01		; Joystick direction defines
JoypadDown		equ	$02	
JoypadLeft		equ	$04	
JoypadRight		equ	$08	
Button1			equ	$10	
Button2			equ	$20	
JoypadUpBit		equ	$00		; Joystick direction bit defines
JoypadDownBit	equ	$01	
JoypadLeftBit	equ	$02	
JoypadRightBit	equ	$03	
Button1Bit		equ	$04	
Button2Bit		equ	$05	
Joysticks		equ	2		; Joysticks supported
JoystickButtons	equ	2		; Joystick buttons supported
